### ISSUE TITLE
[BUG]: Scanning solution seems to not work in pipeline

### ISSUE THREAD

**Issue by starteNCS** [wgnf/liz#146]
### Description of the bug

When scanning my solution I could not get it to work on my azure devops pipeline (ubuntu), where as it works just fine on my local dev machine.

### Steps to reproduce

These are my pipeline steps. Running the exact same on my local machine, does work.
```yml
steps:
  - checkout: self
  - bash: |
      dotnet tool install --global liz.tool
    displayName: Install liz license tool
    workingDirectory: $(Build.SourcesDirectory)
  - task: DotNetCoreCLI@2
    displayName: Restore packages from artifact repository
    inputs:
      command: "restore"
      feedsToUse: "select"
      vstsFeed: "***"
  - bash: |
      liz "./***.sln" --whitelist ./pipelines/licenses.json --suppress-progressbar
    displayName: Check licenses
    workingDirectory: $(Build.SourcesDirectory)
```

### Additional Information

This is the output using the solution:
![image](https://github.com/wgnf/liz/assets/30404993/0a6c3248-7c12-4905-a2a5-93adca531eee)

This is the output I would expect and the output I get when using a csproj:
![image](https://github.com/wgnf/liz/assets/30404993/1adbb281-2b01-4700-9d57-76bc3c52882d)
